/* SPDX-License-Identifier: GPL-2.0-or-later */

#pragma once

#define TAPPING_TOGGLE 2
#define UNICODE_SELECTED_MODES UC_LNX, UC_MAC, UC_WINC
#define VIAL_KEYBOARD_UID {0xC1, 0xB2, 0x7F, 0x95, 0x8A, 0xE5, 0x94, 0xA7}
#define VIAL_UNLOCK_COMBO_ROWS { 0, 9, 5 }
#define VIAL_UNLOCK_COMBO_COLS { 0, 5, 0 }
#define VIAL_ENCODER_DEFAULT {
    KC_VOLU, KC_VOLD, KC_WH_U, KC_WH_D, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
    KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS
}
